### ISSUE TITLE
help originalsrc shash

### ISSUE THREAD

**Issue by 0unknown0shadow0** [papostolopoulos/xPathDataExtraction#1]
how do I get the shash of my url from outlooksafelink.... .. actually if you can explain to me the whole thing that would be very appreciated

**Comment by 0unknown0shadow0** [comment]
<td align="center"><a href="https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fclick.email.oldnavy.com%2F%3Fqs%3D0f8f5db14322a4f41fd758c8749d9271195e85e4995a1c7cd51c09f14ef8eeeeb278a448caa423630051ee9a10f56157f4aa770e516dde0afbef5b19dcd84853&amp;data=02%7C01%7C%7Cf58ad6907e1643f89e2808d6fd65e303%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636975011381208857&amp;sdata=N3y57TpfWun5DPagpFJ5vwYN%2Ftlr43bdX3v6jBZPTuc%3D&amp;reserved=0" originalsrc="https://click.email.oldnavy.com/?qs=0f8f5db14322a4f41fd758c8749d9271195e85e4995a1c7cd51c09f14ef8eeeeb278a448caa423630051ee9a10f56157f4aa770e516dde0afbef5b19dcd84853" shash="UQy9zvHVJEEYXyyo2oA9lfaYRsGBAtGp28RDGI43JbX9zHLAEC53WiXResTBTP3k&#43;dCFt1WXfWSXALYSE58EK5ChmOIbyKqnFqGvQXZ8uJXSODWtRrhDaOBXUInWCFLBnpjzGttE7G50QLW2Qk/VlEVP8b75L7ozQUECIR&#43;fAC4=" target="_blank"><img alt="OLD NAVY" src="http://image.email.oldnavy.com/lib/fe9e13707564037f74/m/42/ON_logo_276x90.png" width="138" height="45" border="0" style="display:block; font-family:Arial,Helvetica,sans-serif; font-size:24px; text-align:center; color:#004373;"></a></td>
        </tr>

**Comment by papostolopoulos** [comment]
It has been a while since I made this so I am not sure what I had done back then. 
There is a video that I had posted online that shows the steps. In essence, you select the different options and hit "enter" or "return". 
As soon as you close the parenthesis or the brackets, the whole function rolls over to the bottom of the page where you can copy it from.
https://youtu.be/YRh_VZG0TJ4

I hope this helps
